{% set version = "0.1.1" %}

package:
  name: pyebsdindex-meta
  version: {{ version }}

source:
  fn: pyebsdindex-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pyebsdindex/pyebsdindex-{{ version }}.tar.gz
  sha256: f0c90afab532e2f015515ed6c4d797a6e97dd772d38855a009f913dd64adb68e

build:
  number: 1

requirements:
  host:
    - python

outputs:
  - name: pyebsdindex-base
    build:
      script: {{ PYTHON }} -m pip install . --no-deps -vv
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - h5py
        - jupyterlab
        - matplotlib-base
        - numba
        - numpy
        - ocl-icd-system  # [linux]
        - ocl_icd_wrapper_apple  # [osx]
        - pyopencl
        - pyswarms
        - python
        - scipy
    test:
      requires:
        - pip
        - pytest
      imports:
        - pyebsdindex
        - pyebsdindex.ebsd_index
        - pyebsdindex.nlpar
        - pyebsdindex.pcopt
      commands:
        - pip check
        - pytest --pyargs pyebsdindex -k "not test_index_pats and not test_pc_optimize and not test_pc_optimize_pso"

  - name: pyebsdindex
    requirements:
      host:
        - python >=3.7
      run:
        - {{ pin_subpackage('pyebsdindex-base', exact=True) }}
        - ray-default  # [not osx]
    test:
      requires:
        - pytest
      imports:
        - pyebsdindex
        - pyebsdindex.ebsd_index
        - pyebsdindex.nlpar
        - pyebsdindex.pcopt
      commands:
        - pytest --pyargs pyebsdindex -k "not test_index_pats and not test_pc_optimize and not test_pc_optimize_pso"

about:
  home: https://pyebsdindex.readthedocs.io
  license_file: License
  license: LicenseRef-PyEBSDIndex
  summary: Python based tool for Hough/Radon based EBSD indexing
  doc_url: https://pyebsdindex.readthedocs.io
  dev_url: https://github.com/USNavalResearchLaboratory/PyEBSDIndex

extra:
  recipe-maintainers:
    - drowenhorst-nrl
    - hakonanes
